apiVersion: apps/v1
kind: Deployment
metadata:
  name: tugraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tugraph
  template:
    metadata:
      labels:
        app: tugraph
    spec:
      containers:
        - name: tugraph
          image: tugraph/tugraph-runtime-centos7:4.1.0
          command: ["/bin/sh", "-c"]
          args:
            - "lgraph_server --directory /var/lgraph_db --log_dir /var/lgraph_log"
          ports:
            - containerPort: 7070
            - containerPort: 7687
          volumeMounts:
            - name: db-storage
              mountPath: /var/lgraph_db
            - name: log-storage
              mountPath: /var/lgraph_log
      volumes:
        - name: db-storage
          hostPath:
            path: /mnt/tugraph/lgraph_db
        - name: log-storage
          hostPath:
            path: /mnt/tugraph/lgraph_log
---
apiVersion: v1
kind: Service
metadata:
  name: tugraph-service
spec:
  selector:
    app: tugraph
  type: NodePort
  ports:
    - name: http
      port: 7070
      targetPort: 7070
      nodePort: 30070
    - name: bolt
      port: 7687
      targetPort: 7687
      nodePort: 30687
