apiVersion: v1
kind: PersistentVolume
metadata:
  name: mono-pg-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mega/mono/pg-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mono-pg-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mono-pg
  template:
    metadata:
      labels:
        app: mono-pg
    spec:
      containers:
        - name: mono-pg
          image: localhost:30500/mono-pg:jenkins-build-3
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: mono-pg-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mono-pg
spec:
  selector:
    app: mono-pg
  ports:
    - port: 5432
      targetPort: 5432
