apiVersion: v1
kind: PersistentVolume
metadata:
  name: mono-engine-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mega/mono/mono-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mono-engine-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mono-engine
  template:
    metadata:
      labels:
        app: mono-engine
    spec:
      containers:
        - name: mono-engine
          image: localhost:30500/mono-engine:${MEGA_RANDOM_IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: proxy-config
          volumeMounts:
            - name: mono-engine-data
              mountPath: /opt/mega
      volumes:
        - name: mono-engine-data
          persistentVolumeClaim:
            claimName: mono-engine-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mono-engine
spec:
  type: NodePort
  selector:
    app: mono-engine
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32001
