apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nativelink-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelink-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nativelink
  template:
    metadata:
      labels:
        app: nativelink
    spec:
      containers:
        - name: nativelink-worker
          image: localhost:30500/nativelink-worker:20250124.1
          imagePullPolicy: Always
          volumeMounts:
            - name: nativelink-storage
              mountPath: /tmp/nativelink
      volumes:
        - name: nativelink-storage
          persistentVolumeClaim:
            claimName: nativelink-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nativelink
spec:
  type: NodePort
  selector:
    app: nativelink
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30051
