constraint_setting(
    name = "rust_toolchain_version",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "default",
    constraint_setting = ":rust_toolchain_version",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "nightly-2025-01-10",
    constraint_setting = ":rust_toolchain_version",
    visibility = ["PUBLIC"],
)
