cargo_env = true
rustc_flags = [
    "-Lnative=$(location :ring-0.17.14-build-script-run[out_dir])",
    "-lstatic=ring_core_0_17_14_",
]

[env]
RING_CORE_PREFIX = "ring_core_0_17_14_"

[buildscript.run.env]
OPT_LEVEL = "3"
