[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
actix-multipart = "0.7"
actix-rt = "2.10"
actix-web = "4.9"
async-trait = "0.1"
anyhow = "1"
assert_cmd = "2.0.10"
axum = { version = "0.7.4", features = ["macros"] }
base64 = "0.22"
bzip2-sys = { version = "0.1.11+1.0.8", features = ["static"] }
cargo_metadata = "0.18"
chrono = "0.4.37"
clap = { package = "clap", version = "4.5.3", features = ["derive"] }
clap-3 = { package = "clap", version = "3.0.9", features = ["derive"] }
crossbeam-utils = "0.8"
csv = "1.1.0"
dotenvy = "0.15.7"
env_logger = "0.11"
filetime = "0.2.14"
futures = "0.3"
futures-util = "0.3"
git2 = "0.19.0"
hyper = { version = "1.2.0", features = ["full"] }
jobserver = "0.1.21"
lalrpop = "0.20.0"
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4.21"
mockito = "1.0.2"
nalgebra = "0.32.4"
neo4rs = "0.7.1"
once_cell = "1.8.0"
plotters = "0.3.5"
postgres = "0.19.7"
pretty_env_logger = "0.5"
rayon = "1.9"
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
regex = "1.10.2"
sanitize-filename = "0.5"
sea-orm = { version = "0.12.15", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "0.5"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
ssh2 = "0.9.4"
structopt = { version = "0.3", default-features = false }
tempfile = "3.10.1"
thiserror = "1"
tokio = { version = "1.36", features = ["full"] }
tokio-postgres = "0.7"
toml = "0.8"
tower-http = { version = "0.5.0", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tugraph = "0.1.4"
tugraph-plugin-util = "0.1.2"
url = "2.2.2"
utoipa = { version = "4.2.0", features = ["axum_extras"] }
utoipa-swagger-ui = { path = "vendor/utoipa-swagger-ui-7.1.0-patch1", features = [
    "axum",
] }
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
walkdir = "2.5"
zip = "2.2.0"

# Local patches - typically git references
[patch.crates-io]
