[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2024"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
actix-multipart = "0.7"
actix-cors = "0.7"
actix-web = "4.10"
async-trait = "0.1"
anyhow = "1.0"
assert_cmd = "2.0"
base64 = "0.22"
bincode = "1.3" # !
bzip2-sys = { version = "0.1.13+1.0.8", features = ["static"] }
cargo_metadata = "0.18" # !
chrono = { version = "0.4", features = ["clock"] }
clap = { package = "clap", version = "4.5", features = ["derive"] }
clap-3 = { package = "clap", version = "3.2", features = ["derive"] }
crossbeam-utils = "0.8"
csv = "1.3"
dotenvy = "0.15"
env_logger = "0.11"
filetime = "0.2"
futures = "0.3"
futures-util = "0.3"
git2 = "0.20"
hyper = { version = "1.6", features = ["full"] }
jobserver = "0.1"
lalrpop = "0.22"
lalrpop-util = { version = "0.22", features = ["lexer", "unicode"] }
lazy_static = "1.5"
libc = "0.2"
libsqlite3-sys = { version = "0.30", features = ["bundled"] } # !
log = "0.4"
mockito = "1.7"
nalgebra = "0.33"
neo4rs = "0.8"
once_cell = "1.21"
pgvector = { version = "0.4", features = ["postgres"] }
plotters = "0.3"
postgres = "0.19"
pretty_env_logger = "0.5"
rayon = "1.10"
rdkafka = { version = "0.37", features = ["cmake-build"] }
redis = "0.30"
regex = "1.11"
reqwest = { version = "0.12", features = ["json"] }
sanitize-filename = "0.6"
sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio"] }
ssh2 = "0.9"
structopt = { version = "0.3", default-features = false }
tempfile = "3.19"
thiserror = "2.0"
tokio = { version = "1.44", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
toml = "0.8"
tower = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
utoipa = { version = "5.3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "=9.0.1", features = [
    "actix-web",
] }
uuid = { version = "1.16", features = ["v4", "fast-rng", "macro-diagnostics"] }
walkdir = "2.5"
zip = "2.6"

# Local patches - typically git references
[patch.crates-io]
utoipa-swagger-ui = { path = "vendor/utoipa-swagger-ui-9.0.1-patch1" }
